track_parcel:
  fields:
    tracking_code:
      required: true
      example: "990000123456"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "990000123456"
      selector:
        text:
